spring:
    data:
        elasticsearch:
            repositories:
                enabled: true
    application:
        name: Elastic-Search-Demo
    elasticsearch:
        uris: http://localhost:9200
        username: elastic
        password: elastic
